- hosts: localhost
  connection: local
  gather_facts: false
  tasks:
    - name: Start EC2 instances with public IPs
      amazon.aws.ec2_instance:
        name: "{{ item.name }}"
        instance_type: t2.micro
        image_id: "{{ item.image }}"
        region: us-east-1
        key_name: "ansible"
        aws_access_key: "{{ aws_access_key }}"
        aws_secret_key: "{{ aws_secret_key }}"
        vpc_subnet_id: "{{ item.subnet }}"
        security_group: "{{ item.sg }}"
        network:
          assign_public_ip: true
        tags:
          Name: "{{ item.name }}"
          Environment: Testing
        wait: true
      loop:
        - { image: "ami-084568db4383264d4", name: "Managed-Node-1", subnet: "subnet-02db3114eacdbf74f", sg: "sg-0b9262fe18b329d87" }
        - { image: "ami-084568db4383264d4", name: "Managed-Node-2", subnet: "subnet-05301e2f3132792a7", sg: "sg-0b9262fe18b329d87" }
        - { image: "ami-0f88e80871fd81e91", name: "Managed-Node-3", subnet: "subnet-04a6e2be31906aa73", sg: "sg-0b9262fe18b329d87" }
      register: ec2_results

    - name: Print EC2 instance details
      debug:
        msg: |
          Instance Name: {{ item.instances[0].tags.Name | default('N/A') }}
          Public IP: {{ item.instances[0].public_ip_address | default('N/A') }}
          Private IP: {{ item.instances[0].private_ip_address | default('N/A') }}
      loop: "{{ ec2_results.results }}"
      loop_control:
        label: "{{ item.instances[0].instance_id }}"
