---
- hosts: webservers
  become: true
  gather_facts: false

  tasks:
    - name: Install openssl and openssl packages
      ansible.builtin.apt:
        name: "{{ item }}"
        state: latest
        update_cache: yes
      loop:
        - openssl
        - openssh
      ignore_errors: yes

    - name: Checking docker is installed or not
      ansible.builtin.command: docker --version
      register: output
      ignore_errors: yes

    - name: Debugging
      ansible.builtin.debug:
        var: output
      ignore_errors: yes

    - name: Installing docker if not installed
      ansible.builtin.apt:
        name: docker.io
        state: present
      when:
        output.failed