---
- hosts: localhost
  connection: local
  gather_facts: no
  tasks:
    - name: Terminate specified EC2 instances
      amazon.aws.ec2_instance:
        instance_ids:
        # Change instance IDs accordingly
          - i-0d9050e5fe57895c4
          - i-05c5e12f5ec59e8b0
        state: absent
        region: us-east-1
