- name: reStart webservice on MultiOS
  ansible.builtin.service:
    name: "{{PKG1 if ansible_distribution == 'Amazon' else PKG2}}"
    state: restarted
    enabled: yes
  when: ansible_distribution == 'Amazon'
